### ISSUE TITLE
Add a 'pause recording' functionality

### ISSUE THREAD

**Issue by imanirajdoost** [natmlx/VideoKit#1]
Currently, with NatDevice, frames can be skipped (by not committing them) to simulate a pause while recording a video. Since VideoKit is out now, it would be cool to add it as a function to the library.

**Comment by olokobayusuf** [comment]
@imanirajdoost first issue 🎊 🎉 . We'll be adding this in the next alpha release, ETA sometime this week.

**Comment by olokobayusuf** [comment]
We've added `PauseRecording` and `ResumeRecording` to `VideoKitRecorder` in [0.0.4](https://github.com/natmlx/VideoKit/releases/tag/0.0.4).
