### ISSUE TITLE
Assembly for Vision Pro

### ISSUE THREAD

**Issue by Polotas** [natmlx/videokit#109]
I can't run tests for Vision Pro because I can't modify the Assembly

![VisionPro](https://github.com/natmlx/videokit/assets/45941721/5bc7b7fc-7204-4011-abfe-980b442cf1e3)

**Comment by Polotas** [comment]
Is there any update on VisionPro?

**Comment by olokobayusuf** [comment]
@Polotas Just invited you to the next alpha. You'll need to manually copy the `ai.natml.videokit` folder in `Packages` and place it in your project's `Packages` folder. You should be good to use visionOS now.

**Comment by olokobayusuf** [comment]
Closing this ahead of the VideoKit 0.0.18 update.
