### ISSUE TITLE
Crash on IOS - VKTRecorderCommitSamples

### ISSUE THREAD

**Issue by Polotas** [natmlx/videokit#111]
I'm having an issue when recording, after 1 or 2 minutes of use the app simply closes. Do you have any idea why this problem is happening?

## Video Kit 0.0.18 alpha 2

![image](https://github.com/natmlx/videokit/assets/45941721/f69adc5a-c897-44a9-9706-8264497e2ca6)

**Comment by Polotas** [comment]
"I updated to **alpha 7**, resolved all conflicts; however, I am unable to record due to this error. I have not modified my setup; would there be any other adjustment required?"

# Error on Init Recording
![Error VideoKit alpha 7](https://github.com/natmlx/videokit/assets/45941721/0d04e186-106c-473f-9cb0-ad93d3e3df6c)

# Setup
![VideoKitSetup](https://github.com/natmlx/videokit/assets/45941721/df81ffb5-4a52-438f-9946-efd542f1097b)

**Comment by olokobayusuf** [comment]
Alpha 8 is coming soon (EOD today or tomorrow) with a substantial rewrite. Hang tight.

**Comment by Polotas** [comment]
Is there any news about the new alpha?
I've been having this problem for 3 weeks and it's causing some concerns among the team.

**Comment by olokobayusuf** [comment]
@Polotas Just invited you to the next alpha. You'll need to manually copy the `ai.natml.videokit` folder in `Packages` and place it in your project's `Packages` folder.

**Comment by olokobayusuf** [comment]
This issue has been fixed in the latest [VideoKit alpha](https://www.npmjs.com/package/ai.natml.videokit) builds.
