### ISSUE TITLE
Failed to upload binary to AppStore Connect

### ISSUE THREAD

**Issue by marvpaul** [natmlx/videokit#115]
I try to upload to AppStore connect. Using "ai.natml.videokit": "0.0.18-alpha.7" / "ai.natml.videokit": "0.0.18-alpha.8". I got this error when uploading the file to iTunes connect (even though it works to build and run locally). I highly assume this happens after a recent update of yours (i was able to upload without this error in a previous version of VideoKit some months ago). 
How can I solve this? 
<img width="1016" alt="Screenshot 2024-04-29 at 18 16 46" src="https://github.com/natmlx/videokit/assets/10696948/78b0bc7f-4c7d-420c-a1b0-774ab8046064">

I also found out that info.plist files look quite weird for the two Frameworks. 
<img width="1425" alt="Screenshot 2024-04-29 at 19 41 46" src="https://github.com/natmlx/videokit/assets/10696948/208a9c24-d12c-419d-b883-4c7a8941357b">

**Comment by marvpaul** [comment]
This is Function Info.plist
[Info.plist.zip](https://github.com/natmlx/videokit/files/15152838/Info.plist.zip)

**Comment by marvpaul** [comment]
I was able to temporary create a workaround by converting the binary file to XML, edit it (add the required values) and convert to binary again. Here is the adjusted file.
[Info.plist.zip](https://github.com/natmlx/videokit/files/15153037/Info.plist.zip)

**Comment by olokobayusuf** [comment]
This has been fixed in the latest alpha build, `0.0.18-alpha.10`.
