### ISSUE TITLE
SetFocusPoint is not working on Android devices.

### ISSUE THREAD

**Issue by haramakoto** [natmlx/videokit#117]
SetFocusPoint in [CameraDevice.cs](https://github.com/natmlx/videokit/blob/main/Runtime/Devices/CameraDevice.cs) does not seem to be working on Android devices.
I kept giving the SetFocusPoint function in Update a Vector2 with x=0.5f, y=0.5f. 
The expected behavior is that the focus is applied to the object in the center of the screen, and the focus shifts as the object in the camera changes, but the focal distance does not change all the time, and the state does not change even if the center of the screen is blurry.

Test device: Pixel7a
Unity version: 2022.3.26f1
Videokit version: 0.0.18 alpha.8

The above is the verification environment, but Videokit 0.0.18 alpha.3, alpha.7, etc. also had the same symptoms.

**Comment by olokobayusuf** [comment]
Confirmed to be a device issue, not a VideoKit issue.
