### ISSUE TITLE
Apple's privacy manifest policy requirements

### ISSUE THREAD

**Issue by knbmedia** [natmlx/videokit#118]
Hello,
I'm still using NatCorder v1.9.4 and NatDevice v1.3.4 on my project.
I have just submited an app update to the AppStore and got a warning about Missing API declarations for categories NSPrivacyAccessedAPICategoryUserDefaults and NSPrivacyAccessedAPICategoryFileTimestamp.
So I'm looking for which framework on my project may use these API, as these frameworks should declare them in their own PrivacyInfo.xcprivacy file.

Your answer on Discord: VideoKit (and the previous libraries) use NSUserDefaults. This will be added to VideoKit, so you'll have to upgrade from NatCorder/NatDevice.

Thank you

**Comment by roycho111** [comment]
Hello @olokobayusuf 

Still using old version of NatCorder that uses NatRender.
Need to know if NatRender uses apis that [Apple listed](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) in order to add to my custom PrivacyInfo file.

Thanks!

**Comment by roycho111** [comment]
VideoKit requires Unity2022+ but i'm still using Unity2020 and i'm good with what old NatCorder offers.
So would it be ok to use VideoKit's privacy manifest with NatRender?

**Comment by Hamjoon** [comment]
@olokobayusuf Please let me know if you provide a wrapper for NSUserDefaults so that it can be called from outside NatCoder. If so, you will need to add a C56D.1 entry and I will work on it manually before the update is released.

**Comment by olokobayusuf** [comment]
> So would it be ok to use VideoKit's privacy manifest with NatRender?

Probably not, because VideoKit does more that NatRender. 

> Please let me know if you provide a wrapper for NSUserDefaults so that it can be called from outside NatCoder.

I'm not sure I understand your question. NatCorder itself doesn't use `NSUserDefaults`. I'm working to push out the privacy info in VideoKit by Monday or Tuesday. I strongly recommend switching to VideoKit; NatCorder won't get any support.

**Comment by olokobayusuf** [comment]
This has been added in the [VideoKit 0.0.18-alpha.16](https://www.npmjs.com/package/ai.natml.videokit) build, and will be published in VideoKit 0.0.18 next week.

**Comment by knbmedia** [comment]
About NatCorder / NatDevice:
I have just published an update to my app on iOS App Store. It was accepted, so there is no need for privacy manifest for these 2 plugins.

**Comment by olokobayusuf** [comment]
This depends on the version of NatCorder and NatDevice you have. Old versions don't use privacy-sensitive APIs.

**Comment by Hamjoon** [comment]
@olokobayusuf From what version is it included in the old version you mentioned? I'm using NatCorder and NatRender.
