### ISSUE TITLE
VideoKit cannot be used with Tensorflow Lite on Android

### ISSUE THREAD

**Issue by alexandrefresnais** [natmlx/videokit#121]
Hey,

I tried to compile my project using both `com.github.asus4.tflite` and VideoKit for Android.

I stumble across the following error:

```
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libtensorflowlite_jni.so' from inputs:
      - /<...>/.gradle/caches/transforms-3/68a13a18f616be0c5924c99dfee13903/transformed/tensorflow-lite/jni/arm64-v8a/libtensorflowlite_jni.so
      - /<...>/.gradle/caches/transforms-3/7ecf52a37ab36433bdb428a4191bcf7e/transformed/NatML/jni/arm64-v8a/libtensorflowlite_jni.so
```

I believe someone mentioned the issue on Discord but no solution was provided.

Thank you in advance

**Comment by olokobayusuf** [comment]
This will be fixed in the 0.0.18 update as we migrate from NatML to [Function](https://fxn.ai). What models are you trying to run with `com.github.asus4.tflite`?

**Comment by olokobayusuf** [comment]
@alexandrefresnais you should migrate to using Function, for better performance, much smoother developer experience, and tight support. Can I show you a tour of the platform?

**Comment by olokobayusuf** [comment]
Closing this ahead of the VideoKit 0.0.18 update. It has been fixed in the latest [VideoKit alpha](https://www.npmjs.com/package/ai.natml.videokit) build.
