### ISSUE TITLE
Logitech C270 takes 2+ minutes to start

### ISSUE THREAD

**Issue by nickhudson4** [natmlx/videokit#125]
Does not appear to happen with other devices.

VideoKit version 0.0.17
Unity Version: 2022.3.9
Windows 11

**Comment by nickhudson4** [comment]
Getting this error when updating to alpha 18. 
`Library\PackageCache\ai.fxn.fxn3d@0.0.20\Runtime\API\FunctionClient.cs(51,25): error CS0433: The type 'IAsyncEnumerable<T>' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

**Comment by olokobayusuf** [comment]
@nickhudson4 what version of Unity are you using? And can you share a screenshot of `Player Settings > Other Settings` in Unity?

**Comment by nickhudson4** [comment]
> Unity Version: 2022.3.9
> Windows 11

![image](https://github.com/natmlx/videokit/assets/44004215/7fcfec47-238f-47a8-88a9-836a13e0aa4f)
![image](https://github.com/natmlx/videokit/assets/44004215/517b7aec-0ad4-43d3-87b2-0cc2fe962836)

**Comment by olokobayusuf** [comment]
@nickhudson4 what happens when you set the `Api Compatibility Level` to `.NET Standard 2.1`?

**Comment by olokobayusuf** [comment]
Okay it seems that this issue exists because your project has a `Microsoft.Bcl.AsyncInterfaces` assembly. Can you reproduce this compiler error in a clean project?

**Comment by nickhudson4** [comment]
I have spent quite a bit of time trying to figure this one out with not much luck. Basically it can be reproduced by adding the `Microsoft.bcl.asyncInterfaces` package to the project with VideoKit. 

Removing the AsyncInterfaces does fix the issue, however, I have numerous other packages that depend on it.

The weird part is that this was not an issue with 0.0.17 of VideoKit. Even though it still uses IAsyncEnumerable. So I wondering if there was anything specific that was changed between these two VideoKit versions?

**Comment by olokobayusuf** [comment]
@nickhudson4 VideoKit depends on [Function](https://github.com/fxnai/fxn3d) which uses `IAsyncEnumerable<T>` from the .NET BCL. If you have other dependencies that also include this interface, then that's technically not an issue with either Function or VideoKit.

Can you confirm that the Logitech camera preview starts instantly on the VideoKit 0.0.18 alpha?

**Comment by nickhudson4** [comment]
The functions library does not rely on BCL `IAsyncEnumerable<T>`. It relies on mscorelib. The issue is that for whatever reason, both mscorelib and BCL both have the same `System.Collection.Generic.IAsyncEnumerable<T>` namespace. So if BCL is anywhere in the project, it creates the conflict. And there are a lot of packages that rely on BCL (Azure.core, System.Text.Json, Xsolla, etc.). So there is a good chance there will be others with this issue. But yes you are right it is not a direct issue with videokit. 

The fix for me was to pull the source of videokit and functions and add them to the project directly with scoped registries. And then check the `Override references` box for both `Functions.Unity.asmdef` and `Functions.Runtime.asmdef`. That way functions is self contained and isn't affected by outside references. 

And yes the alpha 18 fixed the device issue.

**Comment by olokobayusuf** [comment]
@nickhudson4 thanks for confirming.

Regarding `IAsyncEnumerable<T>`, I've enabled `Override references` on both `Function.Runtime` and `Function.Unity` assemblies. This fix will land in the full VideoKit 0.0.18 update.

**Comment by nickhudson4** [comment]
@olokobayusuf Sounds good. Thanks.
