### ISSUE TITLE
Session token creation errors due to failed network request

### ISSUE THREAD

**Issue by olokobayusuf** [natmlx/videokit#127]

**Comment by marvpaul** [comment]
+1 for a quick fix. This makes the version 0.0.18 unusable on iOS and I need it because it fixes some other bugs from the version before

**Comment by olokobayusuf** [comment]
Working on getting clarification from Apple on this issue.

**Comment by olokobayusuf** [comment]
In our investigations so far, this seems Unity-specific. Native web requests aren't being blocked. Will update with more info.

**Comment by olokobayusuf** [comment]
Found a fix. Will publish VideoKit 0.0.19 update by EOD today.

**Comment by olokobayusuf** [comment]
Fixed in 0.0.19.
