### ISSUE TITLE
Camera recording creates a mirrored output

### ISSUE THREAD

**Issue by ctrlaltdel85** [natmlx/videokit#13]
Ideally this would be exposed as a togglable setting

**Comment by olokobayusuf** [comment]
@ctrlaltdel85 for full context, can you share screenshots of the `VideoKitCameraManager` and `VideoKitRecorder` components?

**Comment by ctrlaltdel85** [comment]
<img width="291" alt="Screenshot 2023-02-14 at 3 57 35 PM" src="https://user-images.githubusercontent.com/54692686/218861510-0fa8cce9-0b76-4ba7-a739-35c0aedb59ad.png">
<img width="291" alt="Screenshot 2023-02-14 at 3 52 57 PM" src="https://user-images.githubusercontent.com/54692686/218861571-2fe8a12d-f11c-469c-b600-b3a326e31625.png">
The texture and OnCameraFrame are attached programmatically.

**Comment by olokobayusuf** [comment]
Hey @ctrlaltdel85 what device/platform does this bug occur on?

**Comment by olokobayusuf** [comment]
This should have been fixed in [VideoKit 0.0.10](https://github.com/natmlx/videokit/releases/tag/0.0.10). Feel free to open a new issue if it persists, and make sure to add more info including a screenshot/video, along with configuration, and device.
