### ISSUE TITLE
Memory Crash During Video Recording with NatML VideoKit on iPhone 12 Pro 

### ISSUE THREAD

**Issue by PRO-Spirit** [natmlx/videokit#130]
Hello,

I am currently experiencing a memory crash when I attempt to start recording video using the NatML VideoKit Subscription on my iPhone 12 Pro Max. I subscribed to the NatML VideoKit Subscription primarily to remove the NatML watermark and to improve the quality of video recording. The project was built using Unity and then transferred to an Xcode project, which was subsequently run on my iPhone.

Here are the specifics of the issue and some questions I need clarification on:

Memory Crash on Start: The application crashes due to a memory issue immediately upon starting the recorder. If this problem requires write access on my iPhone, could you guide me on how to configure this permission?

Removal of NatML Badge: I subscribed to the upgraded plan, but I am uncertain whether this plan allows for the removal of the NatML badge during video recording. Can you confirm if this feature is included in the upgraded subscription?

Benefits of the Upgraded Plan: Could you provide a detailed list of the benefits associated with the upgraded plan?

Thank you for your assistance in resolving these issues.

**Comment by olokobayusuf** [comment]
@PRO-Spirit can you share a screenshot of the breakpoint in Xcode when the crash occurs? And also the logs?

> Could you provide a detailed list of the benefits associated with the upgraded plan?

- Record at full resolution
- Record without a watermark
- Record with audio
- Stream the camera
- Stream the microphone
- (coming soon) free credits for speech-to-text
- (coming soon) free credits for text-to-speech
- (coming soon) free credits for human texture streaming (background removal)
- More.

**Comment by PRO-Spirit** [comment]
> Record at full resolution
Is this possible to record as 4k on iphone?
> Record without a watermark
Don't need any addtional setting on unity?

**Comment by PRO-Spirit** [comment]
<img width="1281" alt="Screenshot 2024-06-28 at 02 18 52" src="https://github.com/natmlx/videokit/assets/131204851/34993a25-65e2-4a0e-b3db-4f218e4f68f0">

This is crashed screenshots.

> Bug Report

```
The app “Unity-AR-Camera” has been killed by the operating system because it is using too much memory.
Domain: IDEDebugSessionErrorDomain
Code: 11
Recovery Suggestion: Use a memory profiling tool to track the process memory usage.
User Info: {
    DVTErrorCreationDateKey = "2024-06-27 17:17:01 +0000";
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--
The app “Unity-AR-Camera” has been killed by the operating system because it is using too much memory.
Domain: IDEDebugSessionErrorDomain
Code: 11
Recovery Suggestion: Use a memory profiling tool to track the process memory usage.
User Info: {
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone13,4";
    "device_osBuild" = "17.5.1 (21F90)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "355.28";
    "dvt_mobiledevice_version" = "1643.120.2";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 45259;
    "operation_errorCode" = 11;
    "operation_errorDomain" = IDEDebugSessionErrorDomain;
    "operation_errorWorker" = DBGLLDBLauncher;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 0;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 0;
    "param_diag_gpu_frameCapture_enable" = 1;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 0;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.5";
    "sdk_osVersion" = "17.5";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 14.5 (Build 23F79)
Xcode 15.4 (22622) (Build 15F31d)
Timestamp: 2024-06-28T02:17:01+09:00
```

> This is my unity screen
<img width="1368" alt="Screenshot 2024-06-28 at 02 22 50" src="https://github.com/natmlx/videokit/assets/131204851/8a596b5d-38f5-486f-9a80-57cbf651a34c">
<img width="1382" alt="Screenshot 2024-06-28 at 02 23 16" src="https://github.com/natmlx/videokit/assets/131204851/3b41ed2a-9e84-4dae-b4c0-6b7386263e97">
<img width="1363" alt="Screenshot 2024-06-28 at 02 23 46" src="https://github.com/natmlx/videokit/assets/131204851/db1eaf20-6d30-4300-8d90-b4d24915dcd1">

**Comment by olokobayusuf** [comment]
> Is this possible to record as 4k on iphone?

Yes, but you should only do so when absolutely necessary for your application because this eats up a ton of system resources.

> Don't need any addtional setting on unity?

Nope.

> This is crashed screenshots.

The recording resolution is 3840x8308 which is too large. The `4K` setting in the `VideoKitRecorder` assumes a landscape rotation, but your app is portrait. Change the resolution setting to `Custom` and set it as `2160x3840 ` (notice the width and height are reversed to mirror the portrait orientation).

**Comment by PRO-Spirit** [comment]
Thank you for your support.
Crash issue not appeared, but not saved on my iphone.
This is issue report.

```
VideoKit: MP4Recorder finishing
createImageAtIndex:1532: *** ERROR: createImageAtIndex 3 could not find plugin for image source [1312264 bytes] 00 00 00 1C 66 74 79 70... '....ftyp'
createImageAtIndex:1660: *** ERROR: createImageAtIndex[0] - '....' - failed to create image [-62]
CGImageSourceCreateImageAtIndex:4499: *** ERROR: CGImageSourceCreateImageAtIndex[0] - '....' - failed to create image [-62]
```

**Comment by olokobayusuf** [comment]
Recorded videos are saved to the app's private documents directory. To copy to the camera roll, you have to enable the `Camera Roll` option in the `Recording Action` setting in the `VideoKitRecorder` component.

The `CGImageSourceCreateImageAtIndex:4499` error is innocuous and can be ignored.

**Comment by PRO-Spirit** [comment]
- Can I only record the real environment excluding AR objects because AR is displayed as guide, it does not need to be included in the recorded video.
https://github.com/natmlx/videokit/assets/131204851/75e9c73f-a1a7-4595-8cc1-df756130a8dd

- Can you teach me how can remain the recording action when press the record button, currently recording occurs only as long as the button is pressed.

**Comment by olokobayusuf** [comment]
> Can I only record the real environment excluding AR objects because AR is displayed as guide, it does not need to be included in the recorded video.

Create a second camera that only sees the AR objects, then configure your main camera to not see them. You can do this using layer masks. Once masked, record only the main camera.

> Can you teach me how can remain the recording action when press the record button, currently recording occurs only as long as the button is pressed.

You can write code that calls `StartRecording` and `StopRecording`.

**Comment by PRO-Spirit** [comment]
I set as this camera, but displayed black screen when click the record button and recorded black screen only.
<img width="1369" alt="Screenshot 2024-06-28 at 03 45 36" src="https://github.com/natmlx/videokit/assets/131204851/7cf417e7-bccb-428e-8963-dde5bb36e393">
<img width="1370" alt="Screenshot 2024-06-28 at 03 47 00" src="https://github.com/natmlx/videokit/assets/131204851/367b5cf9-e1a8-4a70-9b91-750bfea0b551">

**Comment by olokobayusuf** [comment]
You need to properly configure the layer masks of the camera. If you are not familiar with how this works, please look up the Unity tutorials. This is not a VideoKit issue.
