### ISSUE TITLE
Adapting Videokit Library for HarmonyOS: Issues with Pre-compiled Libraries

### ISSUE THREAD

**Issue by chenhao8721** [natmlx/videokit#133]
Hi @olokobayusuf,
I hope to install this videokit library on a Huawei's HarmonyOS phone. I plan to modify this library to make it compatible with HarmonyOS, but I found that some of the system-related files under Plugins contain pre-compiled libraries and do not have the source code. What should I do? Or is this library unable to be adapted to HarmonyOS by myself?

**Comment by olokobayusuf** [comment]
Hey @chenhao8721 , from what I've read about HarmonyOS, VideoKit won't be able to run on this operating system. You won't be able to adapt VideoKit to run on the OS. I tried looking at HarmonyOS developer docs but they are sparse.

**Comment by chenhao8721** [comment]
Thank you for your answer!
l still want to ask what the purpose of the compiled files in the Plugins folder is, and whether they are essential to the project. l have the HarmonyOS documentation available to consult: https://gitee.com/openharmony/docs/tree/master/en. It would be great if videokit could run on the HarmonyOS system.

**Comment by olokobayusuf** [comment]
> l still want to ask what the purpose of the compiled files in the Plugins folder is, and whether they are essential to the project.

The native libraries contain the actual implementations of VideoKit for each platform. The C# library wraps the native libraries and provides access to their functionality from C#/Unity. They are required for VideoKit to work.

> l have the HarmonyOS documentation available to consult: https://gitee.com/openharmony/docs/tree/master/en. It would be great if videokit could run on the HarmonyOS system.

The docs seem useful, but adding a new platform to VideoKit is not an easy undertaking, especially given that you're the only one who has requested this. It sounds like you are familiar enough with HarmonyOS, so perhaps you can implement this backend yourself? Feel free to [follow up over email](mailto:hi@videokit.ai)
