### ISSUE TITLE
0.0.19 can't record on iOS and editor, cannot create session token

### ISSUE THREAD

**Issue by marvpaul** [natmlx/videokit#136]
Suddenly I can't record on iOS and in the editor anymore, even though it worked before with the same build and I have a valid subscription key which I added to Unity. 

InvalidOperationException: Cannot create session token because your access key is invalid
VideoKit.Internal.VideoKitClient.CreateSessionToken (System.String buildToken) (at ./Library/PackageCache/ai.natml.videokit@0.0.19/Runtime/Internal/VideoKitClient.cs:165)
VideoKit.Internal.VideoKitClient.CheckSession () (at ./Library/PackageCache/ai.natml.videokit@0.0.19/Runtime/Internal/VideoKitClient.cs:58)
VideoKit.MediaRecorder.Create (VideoKit.MediaRecorder+Format format, System.Int32 width, System.Int32 height, System.Single frameRate, System.Int32 sampleRate, System.Int32 channelCount, System.Int32 videoBitRate, System.Int32 keyframeInterval, System.Single compressionQuality, System.Int32 audioBitRate, System.String prefix) (at ./Library/PackageCache/ai.natml.videokit@0.0.19/Runtime/MediaRecorder.cs:176)
VideoKit.VideoKitRecorder.StartRecording () (at ./Library/PackageCache/ai.natml.videokit@0.0.19/Runtime/Components/VideoKitRecorder.cs:481)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <8f2b770c4a1b401a99ba9ed80a5c09b9>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

Also in the web dashboard my current plan looks weird. It says that it cancels this month but it will not (at least I didn't canceled the subscription). 
<img width="1466" alt="Screenshot 2024-07-15 at 09 37 26" src="https://github.com/user-attachments/assets/b642d9c4-ac6c-44c5-8481-94668dcec290">

**Comment by marvpaul** [comment]
Found out that the old website and token is not working anymore. I was able to generate a new token from here: https://www.videokit.ai/

**Comment by olokobayusuf** [comment]
@marvpaul sorry for the confusion. We've moved VideoKit to its own website, [videokit.ai](https://videokit.ai). We'll send out an email announcement this week.
