### ISSUE TITLE
When recording from texture with camera running, the camera turns black and stutters in the first few frames

### ISSUE THREAD

**Issue by ctrlaltdel85** [natmlx/videokit#14]
It seems like the camera device is being reset at the start of recording, along with some stuttering

**Comment by olokobayusuf** [comment]
Hey @ctrlaltdel85 can you share an example video showing this bug? And what version of VideoKit are you on?

**Comment by ctrlaltdel85** [comment]
https://user-images.githubusercontent.com/54692686/219899998-39e88fdd-4470-41dd-95b0-5d517a67e7f2.mp4

This is a video taken with VideoKit 0.0.9 with Unity 2022.2.6 on MacOS. The black doesn't happen on the iPhone, but instead I get a noticeable 0.5 second stutter. I'm currently working on ways to skip the video playback to start at a certain point, unless you think the stutter can be fixed.

**Comment by olokobayusuf** [comment]
Oh a stutter at the very start of your first recording typically happens because the OS is provisioning the hardware encoder. It is impossible to avoid this, and it should only happen on your very first recording. Can you confirm whether it happens in subsequent recordings?

Also, that's a cool bar you're at 😎

**Comment by ctrlaltdel85** [comment]
The UI stutters for a moment in subsequent recordings but the recording seems fine. Does the stutter only happen when the camera is enabled? I'm thinking of creating a tiny recording at the start of the app to initialize the recorder.

Btw I'm at the cafe above the comedy cellar in NYC!

**Comment by olokobayusuf** [comment]
> The UI stutters for a moment in subsequent recordings but the recording seems fine. Does the stutter only happen when the camera is enabled? I'm thinking of creating a tiny recording at the start of the app to initialize the recorder.

I'll add this to the `VideoKitRecorder` so you don't have to.

> Btw I'm at the cafe above the comedy cellar in NYC!

Oh shit! I'm in NYC too, let's meet up :D . I'll DM you on Discord.

**Comment by olokobayusuf** [comment]
Also @ctrlaltdel85 back to the original issue, I think this might stem from the fact that you're recording from a texture. Just to confirm: are you assigning the recording texture **before** you start recording? In the next update, we'll be requiring this.

**Comment by olokobayusuf** [comment]
This should be fixed in [VideoKit 0.0.10](https://github.com/natmlx/videokit/releases/tag/0.0.10).
