### ISSUE TITLE
Add functionality to "warm-up" recorder, to avoid stall on first recording.

### ISSUE THREAD

**Issue by supermoos** [natmlx/videokit#16]
As per discord discussion there's a stutter / lag happening at the beginning of the first recording. The suggested workaround from discord thread is: "The workaround is pretty simple: create a recorder, commit exactly one video frame (empty array), then finish recording and delete the file.
Best done in a loading screen" - would be nice to have some helper function that could be called that does this.

**Comment by olokobayusuf** [comment]
@supermoos we've added this as a toggle in `VideoKitRecorder`. It's called `prepareOnAwake` and will run this preparation when the component awakes (on scene load, or when you instantiate the component from code). This will be in the next update.

**Comment by olokobayusuf** [comment]
Implemented in [VideoKit 0.0.10](https://github.com/natmlx/videokit/releases/tag/0.0.10)
