### ISSUE TITLE
Unity freezes during unstable network connections

### ISSUE THREAD

**Issue by ctrlaltdel85** [natmlx/videokit#18]
SocketException: No such host is known
System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
Rethrow as HttpRequestException: No such host is known
System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) (at <29bbdedb06b44b60bf32f833977d7bd1>:0)
NatML.Hub.NatMLHub.RequestNet[TRequest,TResponse] (TRequest request, System.String accessKey) (at ./Library/PackageCache/ai.natml.hub@1.0.20/Runtime/NatMLHub.cs:196)
NatML.Hub.NatMLHub.GetUser (System.String accessKey) (at ./Library/PackageCache/ai.natml.hub@1.0.20/Runtime/NatMLHub.cs:77)
Rethrow as AggregateException: One or more errors occurred. (No such host is known)
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <434571214be741f48f7262e1e0f039a1>:0)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <434571214be741f48f7262e1e0f039a1>:0)
System.Threading.Tasks.Task`1[TResult].get_Result () (at <434571214be741f48f7262e1e0f039a1>:0)
NatML.Hub.Editor.HubProjectSettings.CreateSettings (System.Boolean refresh) (at ./Library/PackageCache/ai.natml.hub@1.0.20/Editor/HubProjectSettings.cs:46)
NatML.Hub.Editor.HubProjectSettings.OnLoad () (at ./Library/PackageCache/ai.natml.hub@1.0.20/Editor/HubProjectSettings.cs:64)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <434571214be741f48f7262e1e0f039a1>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

**Comment by olokobayusuf** [comment]
This will be fixed in the next update.

**Comment by olokobayusuf** [comment]
This has been fixed in the [0.0.14-alpha.1](https://www.npmjs.com/package/ai.natml.videokit) pre-release build. Closing this issue early to declutter.
