### ISSUE TITLE
Add option to record VideoKitCameraView as one of VideoKitRecorder's Video Modes

### ISSUE THREAD

**Issue by Malyglut** [natmlx/VideoKit#2]
Currently `VideoKitRecorder` allows for recording of Camera, Screen or Texture. 

With `VideoKitCameraView` allowing us to display the camera feed on a `RawImage` i think it would be a common use case to record the `RawImage`'s Texture itself.

Currently it is possible to achieve this effect with a workaround involving another `VideoKitCameraView` rendered on a `Canvas` with Render Mode set to Screen Space - Camera then setting `VideoKitRecorder`'s Video Mode to Camera and setting the camera to the one on which the `Canvas` is overlayed.

**Comment by olokobayusuf** [comment]
We've added preliminary support for this in [0.0.4](https://github.com/natmlx/VideoKit/releases/tag/0.0.4) with the new `VideoKitRecorder.VideoMode.CameraDevice` video mode. It currently has a limitation in that the recording resolution **must** have the same aspect ratio as the camera preview. We will lift this limitation in a coming update.
