### ISSUE TITLE
Safari with NatML

### ISSUE THREAD

**Issue by tomaszwozniak123** [natmlx/videokit#21]
Hi @lanreolokoba @olokobayusuf 

I know there is no support for Safari, but maybe there is some solution for working with that browser?
When building sample project for Meet Segmentation I get this error in Safari:
```
abort({}) at jsStackTrace@https://v6p9d9t4.ssl.hwcdn.net/html/7579938/Build/Build.framework.js:3:25512
stackTrace@https://v6p9d9t4.ssl.hwcdn.net/html/7579938/Build/Build.framework.js:3:25797
abort@https://v6p9d9t4.ssl.hwcdn.net/html/7579938/Build/Build.framework.js:3:1002
https://v6p9d9t4.ssl.hwcdn.net/html/7579938/Build/Build.framework.js:3:20377
promiseReactionJob@[native code]
```

Thanks in advance for any help

**Comment by olokobayusuf** [comment]
Safari support will be coming in Safari 16.4, with the addition of WASM SIMD.

**Comment by tomaszwozniak123** [comment]
@olokobayusuf 
hi, thanks for info. 
I have already tested on Safari 16.4 (installed from here: [techspot_Safari16.4](https://www.techspot.com/downloads/downloadnow/4185/?evp=e88fa7dde729eadd7478088bf9808c66&file=10016)) - and I got same error. Could you please confirm for sure that it should work on 16.4?

**Comment by olokobayusuf** [comment]
I responded to you on Discord. The latest Safari 16.4 Technical Preview supports NatML, and I'm able to create and use an `MLEdgeModel`. Let's continue the convo on Discord.

**Comment by tomaszwozniak123** [comment]
just for someone searching for solution: it works on Safari 16.4 with macOS Ventura (it does not run on Monterey for me).
