### ISSUE TITLE
Safari 16.4 StopRunning() camera doesn't stops camera.

### ISSUE THREAD

**Issue by tomaszwozniak123** [natmlx/videokit#25]
We have found that on Safari 16.4 after StopRunning() camera, the camera device is still running. (We see camera icon in browser and diode is on)
WebGL, Unity 2021.3.20.
![image](https://user-images.githubusercontent.com/125497638/229531957-2908c8d1-df86-41ec-ab8e-0d7ba5d5be80.png)

**Comment by olokobayusuf** [comment]
This also seems to happen on Firefox.

**Comment by olokobayusuf** [comment]
[Fixed in VideoKit 0.0.13](https://github.com/natmlx/videokit/releases/tag/0.0.13).
