### ISSUE TITLE
Android Build Fails when using AVPro plugin

### ISSUE THREAD

**Issue by tomihr** [natmlx/videokit#27]
Hello I am getting this error when trying to build APk that is using VideoKit 
![image](https://user-images.githubusercontent.com/439072/234076064-2916e838-e931-4ece-a628-7f562ebcb1a6.png)
When I remove VideoKit it builds with no errors.
It happens when I import the AVPro plugin.
Here is a test project.
https://drive.google.com/file/d/1HxO0c3zUfv5a439E_dg0cRH5HmsGhJ-h/view?usp=sharing

**Comment by olokobayusuf** [comment]
One of our users was able to find a solution to this: [here you go](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/153#issuecomment-1100119239).
