### ISSUE TITLE
Request the ability of trimming videos using VideoKit

### ISSUE THREAD

**Issue by emrullaharsay** [natmlx/videokit#29]
Hi. I need to trim or cut videos before exporting/sharing.  If it's not too big of a hassle, It would be great to be able to do it using VideoKit and not adding another video api/sdk specifically for this. Thanks.

**Comment by olokobayusuf** [comment]
@emrullaharsay this is a good feature. Just to confirm, you only want to trim the video to a specific length?

**Comment by emrullaharsay** [comment]
Mainly what we are gonna implement is trimming video from start and end with a slider like in most of other video apps or  native video trimming feature that exists in both IOS and android.
![trimmer](https://user-images.githubusercontent.com/17803517/235623072-c7d5eae5-dcb6-4b01-8410-f81c816d2a65.jpg)
So I assumed if we can cut in half, we can cut other predetermined time value. :) so basically what i want is cut specific predetermined time from video from both ends. Thanks a lot for your work btw.

**Comment by olokobayusuf** [comment]
Sounds good. Just wanted to clarify that you also wanted the UI.

**Comment by emrullaharsay** [comment]
Oh no. I just put that image to show how I want to cut or trim the video. Dont waste your valuable time on the visuals.

**Comment by olokobayusuf** [comment]
@emrullaharsay we've decided not to add video trimming or other editing functions to VideoKit. Instead, we recommend using our [Function](https://fxn.ai) platform to implement your own trimming function. Let me know if you're still interested in this so I can walk you through the implementation.
