### ISSUE TITLE
Events for VideoKitCameraView

### ISSUE THREAD

**Issue by Malyglut** [natmlx/VideoKit#3]
Due to a delay between calling `VideoKitCameraManager.StartRunning()` and the camera actually being rendered to `VideoKitCameraView` it would be nice to have a set of events that would allow for performing actions when the camera feed starts/finishes being rendered onto the texture.

**Comment by olokobayusuf** [comment]
We've added an `OnPresent` event to the `VideoKitCameraView` component in [0.0.4](https://github.com/natmlx/VideoKit/releases/tag/0.0.4).
