### ISSUE TITLE
Need way to separate and then combine recording of audio and video

### ISSUE THREAD

**Issue by ctrlaltdel85** [natmlx/videokit#33]
I'm working on a project which performs post processing on a video. Each video frame needs to be processed and committed to back to the recording at the original frame's timestamp. In order for the audio to sync up, the audio needs to be transplanted to the new recording as well.

**Comment by olokobayusuf** [comment]
This is in the works for the next VideoKit update.

**Comment by olokobayusuf** [comment]
@ctrlaltdel85 We've decided to not implement video editing functions in VideoKit because of how open-ended editing gets. Instead, I recommend using our [Function](https://fxn.ai) platform to implement an editing pipeline. Let me know if you're interested and I can get you setup.
