### ISSUE TITLE
How to / Add feature for: Read out ISO value of camera 

### ISSUE THREAD

**Issue by max-critcrew** [natmlx/videokit#35]
We are currently digging deeper into the SDK and we realized that it's possible to get the ISO-range, but not the current ISO-value. Getting the exposure value works, just not the ISO.
We need to get the actual value to display in a slider (current value, and min/max as the ends of the slider)

Is it possible to get/access the current ISO value somehow already / could this feature be added?

**Comment by olokobayusuf** [comment]
Coming in the next update, along with `exposureDuration`.

**Comment by olokobayusuf** [comment]
This has been added in the [0.0.14-alpha.1](https://www.npmjs.com/package/ai.natml.videokit) pre-release build. Closing this issue early to declutter. We've added `CameraDevice.exposureDuration` and `CameraDevice.ISO`.
