### ISSUE TITLE
Expose `frameDuration` when using GifRecorder

### ISSUE THREAD

**Issue by supermoos** [natmlx/videokit#37]
Is it possible to expose the frameDuration so that one can manually define the GifRecorder's frame delay? It's private right now.

**Comment by olokobayusuf** [comment]
Sounds good. Will add it in the next update.

**Comment by olokobayusuf** [comment]
This has been added in the [0.0.14-alpha.1](https://www.npmjs.com/package/ai.natml.videokit) pre-release build. Closing this issue early to declutter.
