### ISSUE TITLE
Embedded unity With IOS using video kit 0.0.13

### ISSUE THREAD

**Issue by Aditya-Solulab** [natmlx/videokit#41]
Hi I Embedded my unity with IOS. App crash with the error
Helped for embed unity With IOS : https://docs.unity3d.com/2021.3/Documentation/Manual/UnityasaLibrary-iOS.html
Repo that provided by unity : https://github.com/Unity-Technologies/uaal-example/blob/master/docs/ios.md
Library not loaded: @rpath/NatDevice.framework/NatDevice

dyld[5945]: Library not loaded: @rpath/NatDevice.framework/NatDevice
  Referenced from: <88AF24F6-A3C6-3B42-880B-232B72490096> /private/var/containers/Bundle/Application/7EA307FF-438C-483F-90AF-9C57B5FB774D/NativeiOSApp.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/private/var/containers/Bundle/Application/7EA307FF-438C-483F-90AF-9C57B5FB774D/NativeiOSApp.app/Frameworks/NatDevice.framework/NatDevice' (no such file), '/private/var/containers/Bundle/Application/7EA307FF-438C-483F-90AF-9C57B5FB774D/NativeiOSApp.app/Frameworks/NatDevice.framework/NatDevice' (no such file), '/private/var/containers/Bundle/Application/7EA307FF-438C-483F-90AF-9C57B5FB774D/NativeiOSApp.app/Frameworks/NatDevice.framework/NatDevice' (no such file), '/System/Library/Frameworks/NatDevice.framework/NatDevice' (no such file, not in dyld cache)
  
  Thanks in advance

**Comment by olokobayusuf** [comment]
Hey @Aditya-Solulab , in your Xcode project, can you confirm that in the General settings > Embedded frameworks, `NatDevice.framework` is set to `Embed`?

**Comment by ankitsolulab** [comment]
Hello @olokobayusuf added NetDevice.framework, NatMLHub.framework, NatCoder.framework and NatML.framework in to embed libraries. But, we are still facing issue with crash on app launch.

Please refer below attached screenshots.
<img width="1416" alt="Screenshot 2023-07-17 at 11 13 31 AM" src="https://github.com/natmlx/videokit/assets/17784971/90474b7f-9ea9-4b97-b113-51dac55da543">

After doing above step we are trying to run the app but facing crash issue with NO logs.
<img width="1430" alt="Screenshot 2023-07-17 at 11 15 10 AM" src="https://github.com/natmlx/videokit/assets/17784971/dcffb90d-c4b3-4a05-ab4e-a00e4eb3ff97">

Thanks.

**Comment by olokobayusuf** [comment]
@ankitsolulab what is your native app's minimum iOS deployment target?

**Comment by ankitsolulab** [comment]
@olokobayusuf  It is 16.4.

**Comment by ankitsolulab** [comment]
@olokobayusuf Yes, It is minimum deployment target and in iPhone XR OS version is 16.5.1 (C).

**Comment by ankitsolulab** [comment]
@olokobayusuf  When we added libraries it also added in to "Link binary with Library" In Build phases. We have to remove it to run app. before we are getting error what we posted.

**Comment by olokobayusuf** [comment]
Hey @ankitsolulab , can you try out the [VideoKit 0.0.14 alpha 2](https://www.npmjs.com/package/ai.natml.videokit) build? Follow the setup instructions on that page, then do a clean build from Unity (don't append). Let me know if the issue persists.

**Comment by olokobayusuf** [comment]
This should be fixed in [VideoKit 0.0.14](https://github.com/natmlx/videokit/releases/tag/0.0.14).
