### ISSUE TITLE
Higher preview resolution looks blurry on windows

### ISSUE THREAD

**Issue by tufeixp** [natmlx/videokit#46]
I was playing the demo project with a stereo cameras, with resolution support like 640x376(single view),1280x376(dual views), 2560x800, 3840x1080.
However, not matter how high I config the previewResolution and MP4Recorder.videoWidth, the result preview resolution I get on screen looks like a very low resolution.
Then I updated natdevice to 1.3.1 and natcorder to 1.9.1, still the same results: Even I set the preview resolution to 640x376, the result is a blurry dual view.

I just set screen resolution to : 640,376 and added two prints as:
cameraDevice = query.FirstOrDefault(device => device is CameraDevice) as CameraDevice;
cameraDevice.previewResolution = (playWidth, playHeight);
//cameraDevice.photoResolution = (1920, 1080);
print(" resolutions preview: " + cameraDevice.previewResolution.width + " : " + cameraDevice.previewResolution.height);
audioDevice = query.FirstOrDefault(device => device is AudioDevice) as AudioDevice;
// Start the camera preview
previewTextureOutput = new TextureOutput();
cameraDevice.StartRunning(previewTextureOutput);
// Display the preview texture
var previewTexture = await previewTextureOutput;
previewImage.texture = previewTexture;
previewAspectFitter.aspectRatio = (float)previewTexture.width / previewTexture.height;
print(" previewTexture "+ previewTexture.width + " : " + previewTexture.height);

The result is :
resolutions preview: 640 : 376
previewTexture 640 : 376

https://user-images.githubusercontent.com/11953709/200452187-b7a53ff9-7eb1-44ab-b80d-19f2e9acd1ed.png

**Comment by olokobayusuf** [comment]
Closing this issue as it should be fixed in VideoKit 0.0.18. Feel free to test the [VideoKit alpha](https://www.npmjs.com/package/ai.natml.videokit), and create a new issue if this still occurs.
