### ISSUE TITLE
Using RGB stream causes Logitech webcam startup delay

### ISSUE THREAD

**Issue by V0odo0** [natmlx/videokit#47]
We have HD Pro Webcam C920 and B525 HD Webcam. For them, it takes around one minute to start receiving frames. Same delay when changing resolution.

* It happens only on laptops. Tested on two different laptops with clean Win11
* No issues on Win11 PCs and other platforms
* Other types of webcams is OK
* Other apps like OBS, Skype etc. has no such big delay

**Comment by olokobayusuf** [comment]
This has been fixed in the upcoming VideoKit 0.0.18 update, and has been implemented in the [current alpha builds](https://www.npmjs.com/package/ai.natml.videokit).
