### ISSUE TITLE
Add watermark to recordings with WatermarkTextureInput

### ISSUE THREAD

**Issue by yuchenz27** [natmlx/VideoKit#5]
We can add watermark with the use of `WatermarkTextureInput` in NatCoder.

Is that possible now to add watermark functionality with `WatermarkTextureInput` into `VideoKitRecorder`?

Thank you very much.

**Comment by marvpaul** [comment]
+1, would love to see this!

**Comment by olokobayusuf** [comment]
This has been implemented in VideoKit 0.0.6.
