### ISSUE TITLE
`GLESTextureInput` crash when starting recording

### ISSUE THREAD

**Issue by Tillmania** [natmlx/videokit#55]
pid: 0, tid: 32181 >>> com.gravytraingames.santatrackerlitereal <<<

backtrace:
  #00  pc 0x00000000000300fc  /system/lib64/libmediandk.so (AImageReader_getWindow.cfi+28)
  #01  pc 0x0000000000137b10  /data/app/v6ONcEUrYEzV0qofrSCctg==/com.gravytraingames.santatrackerlitereal-pTWmJdtW3OPSphDJOtyU1A==/lib/arm64/libVideoKit.so (VideoKit::Recorders::GLESTextureInput::Readback(void*)+208)
  #02  pc 0x000000000013816c  /data/app/v6ONcEUrYEzV0qofrSCctg==/com.gravytraingames.santatrackerlitereal-pTWmJdtW3OPSphDJOtyU1A==/lib/arm64/libVideoKit.so
  #03  pc 0x00000000000c1b40  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_start(void*)+224)
  #04  pc 0x0000000000054f20  /apex/com.android.runtime/lib64/bionic/libc.so (start_thread+64)

**Comment by olokobayusuf** [comment]
[Fixed in VideoKit 0.0.15](https://github.com/natmlx/videokit/releases/tag/0.0.15).
