### ISSUE TITLE
Error Unity Curl error 60: Cert verify failed. Certificate has expired. UnityTls error code: 7 - Causes Crash

### ISSUE THREAD

**Issue by max-critcrew** [natmlx/videokit#58]
On some older devices, if you call StartRunning, it will not actually start - instead the camera will stay black since the sessionToken is null due to the Unity error.

Reference:
https://forum.unity.com/threads/curl-error-60-cert-verify-failed-unitytls_x509verify_flag_expired-ssl-ca-certificate-error.1204672/#post-7697590

![image](https://github.com/natmlx/videokit/assets/86074507/7c258885-6952-40f6-ae84-62fd5eb8d650)

**Comment by olokobayusuf** [comment]
Because the underlying error is from the device's certificates (not even Unity in this case), there's nothing we (or Unity) can do to fix it. Closing this one out.

**Comment by max-critcrew** [comment]
@olokobayusuf If we only use offline features - is there any way that we do not need to authenticate? Can you create the session token at compile time?
