### ISSUE TITLE
VideoStabilizationMode() - Crash on Android native

### ISSUE THREAD

**Issue by max-critcrew** [natmlx/videokit#59]
On Android, we're about to publish the app and in the "Pre-launch report" the Google Play Console is reporting a crash on a motorola android debug with the last thing inthe stack trace being:

`lib/arm64/libVideoKit.so (VideoKit::Devices::CameraDevice::VideoStabilizationMode() const+64)`

![image](https://github.com/natmlx/videokit/assets/86074507/c5fac95d-7f95-487f-bef7-37b6cd141fe0)

**Comment by olokobayusuf** [comment]
[Fixed in VideoKit 0.0.15](https://github.com/natmlx/videokit/releases/tag/0.0.15).
