### ISSUE TITLE
Recording resolution is incorrect when the orientation is portrait

### ISSUE THREAD

**Issue by yuchenz27** [natmlx/VideoKit#6]
I am using VideoKit on an iPhone with the following settings

![image](https://user-images.githubusercontent.com/44870300/209821274-8885f7b5-065d-4350-9713-dc32e355032d.png)

But the video I got was in 2796 * 1290, which was not a portrait one.

Regarding to Lanre from Discord:

"When the `Resolution` is `Screen` or `HalfScreen` and the `Orientation` is not `Landscape`, then the output resolution will actually be landscape. The fix is to either change the `Resolution` to not be `Screen` or `HalfScreen`; or set the `Orientation` to `Landscape` when using either of these modes."

**Comment by olokobayusuf** [comment]
This has been fixed in VideoKit 0.0.6.
