### ISSUE TITLE
IOS build error of Xcode(ver. 15)  workspace  which is generated by Unity 2022.3.10f1 LTS.

### ISSUE THREAD

**Issue by jhdot** [natmlx/videokit#61]
![image](https://github.com/natmlx/videokit/assets/145401214/de907868-6e65-4c49-80df-7365bdb5bfee)

**Comment by 18AX** [comment]
I have the same problem, have you found any solution ?

**Comment by olokobayusuf** [comment]
Fix coming in VideoKit 0.0.15.

**Comment by olokobayusuf** [comment]
[Fixed in VideoKit 0.0.15](https://github.com/natmlx/videokit/releases/tag/0.0.15).
