### ISSUE TITLE
Camera Usage Description error.

### ISSUE THREAD

**Issue by jhdot** [natmlx/videokit#62]
I'm not using web camera, so I disabled it. Then following error happens when I try to build iOS.
![Screenshot 2023-10-06 at 3 41 24 PM](https://github.com/natmlx/videokit/assets/145401214/814f02dd-166e-4cf8-be24-9d354fae245f)
So I have to comment out an api which has WebCamTexture argument.

**Comment by jhdot** [comment]
BuildFailedException: Player build failed: WebCamTexture class is used but Camera Usage Description is empty in Player Settings.
System.Exception: WebCamTexture class is used but Camera Usage Description is empty in Player Settings.
   at PlayerBuildProgramLibrary.FeatureExtractor.Run(CSharpActionContext ctx, Data data) in /Users/bokken/build/output/unity/unity/Editor/IncrementalBuildPipeline/PlayerBuildProgramLibrary/FeatureExtractor.cs:line 38

UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/build/output/unity/unity/Editor/Mono/Modules/BeeBuildPostprocessor.cs:718)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <493401b5f0134d428851d72dabe2e798>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:190)

**Comment by olokobayusuf** [comment]
This isn't a VideoKit bug. VideoKit doesn't have any uses of `WebCamTexture`.
