### ISSUE TITLE
iOS 17 Sharing Issue

### ISSUE THREAD

**Issue by Tillmania** [natmlx/videokit#63]
When attempting to share using any MediaAsset object the sharing dialogue often fails and locks up the UI

**Comment by olokobayusuf** [comment]
Looked into this, [it's an iOS 17 bug](https://developer.apple.com/forums/thread/727838), and does not prevent the sharing UI from popping up. It just glitches for a moment. Can you confirm?

**Comment by olokobayusuf** [comment]
Just confirmed, none of the workarounds work; it's an iOS 17 issue.

**Comment by Tillmania** [comment]
A lot of the time it will enter a weird feedback loop where it will keep popping up the share sheet only for it to disappear. Is it an issue with Unity or iOS 17 itself?

**Comment by olokobayusuf** [comment]
It's iOS 17, not Unity. Hopefully Apple pushes a fix soon.

**Comment by Tillmania** [comment]
Ok no worries, appreciate you looking into it
