### ISSUE TITLE
Website Sign up. allways show loading, can't Create Account. [Sign up]

### ISSUE THREAD

**Issue by guanghui1987** [natmlx/videokit#65]
Web Page
https://www.fxn.ai/login
Create account Begin your ML journey in only a few clicks.

desc:
After input name,  I click 'Create Account' button.  it allways show loading.

API error:
POST https://api.fxn.ai/graph/graph 400 (Bad Request)

some exceptions stack
_app-bf78e11a2539c3cb.js:6 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
    at Object.register [as onSubmit] (login-ffb97b07163e2cb3.js:1:17814)

**Comment by olokobayusuf** [comment]
Hey @guanghui1987 , were you able to get past this error? Has it happened again?
