### ISSUE TITLE
Issue in JPEG image sequences

### ISSUE THREAD

**Issue by thesanketkale** [natmlx/videokit#66]
I am seeing some issues while taking JPEG image sequences using the VideoKitRecorder component. The JPEG images have some patches at the bottom of the images (Sample shared below). The mp4 video is coming fine, only the JPEG sequences bear the issue.

<img src="https://github.com/natmlx/videokit/assets/36810188/475d1ebe-7c51-4383-98c3-a196de254081" width="300">

When tried in a separate UI, the image sequences are not all saved in the target folder when taken using the VideoKitRecordButton prefab.

Unity version: 2023.1.15f1
Build platform: Android
Color space: Linear

I use almost standard settings here except for custom resolution of 1080 x 1920.

**Comment by olokobayusuf** [comment]
This has been fixed in the upcoming VideoKit 0.0.18 update. Feel free to test the current [VideoKit alpha](https://www.npmjs.com/package/ai.natml.videokit).
