### ISSUE TITLE
Longer video dosen't get saved

### ISSUE THREAD

**Issue by marvpaul** [natmlx/videokit#67]
As we discussed I just open an issue here because some customers complained that longer recordings often fail. You mentioned that's most probably could be caused by time shifting issues caused by a not accurate clock and that you plan to include a native implementation of the clock to have better accuracy.

**Comment by marvpaul** [comment]
No more complains where reported from my customers - thank you!

**Comment by olokobayusuf** [comment]
Sounds great!
