### ISSUE TITLE
Option to fetch mic data 

### ISSUE THREAD

**Issue by marvpaul** [natmlx/VideoKit#7]
Feature request:
In my music visualization app I use NatDevice to access the microphone and process the audio data to finally visualize it (FFT …). I also use the same audio data to feed NatCorder, so it can record the microphone audio and include it in the video. Is the same possible using VideoKit (commit audio data from NatDevice)?

Your response on discord: “ Not yet; the current API doesn't expose a way to extract the audio data while recording. I recommend opening an issue for this; we can pretty easily expose an API to allow you to receive mic audio while it's being streamed.https://github.com/natmlx/VideoKit”

It would be great to have this feature - thanks!

**Comment by olokobayusuf** [comment]
This is in the works 😄

**Comment by olokobayusuf** [comment]
We've added the `VideoKitAudioManager` component, which exposes an `OnSampleBuffer` event that can be plugged into. Docs incoming.
