### ISSUE TITLE
VideoKit fails to start on user's Windows device - Invalid Session Token

### ISSUE THREAD

**Issue by pnostudiodeveloper** [natmlx/videokit#86]
I built my app for Windows using:

VideoKit 0.0.17
Unity 2021.3.31

VideoKit functionality works fine on the Windows 11 laptop I have for testing - I've tested thoroughly and can't reproduce this issue on my own computer.

However, I've received an email from a user that says Live Camera functionality isn't working for them at all, with the following VideoKit crash in the log:

Uploading Crash Report
InvalidOperationException: VideoKit session token is invalid. Check your NatML access key.
  at VideoKit.Internal.VideoKit.CheckStatus (VideoKit.Internal.VideoKit+Status status) [0x00000] in <00000000000000000000000000000000>:0 
  at VideoKit.Devices.CameraDevice.StartRunning (System.Action`1[T] handler) [0x00000] in <00000000000000000000000000000000>:0 
  at VideoKit.VideoKitCameraManager.set_device (VideoKit.Devices.CameraDevice value) [0x00000] in <00000000000000000000000000000000>:0 
  at LiveCamera.StartCameraAsync () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 

Attaching full log file as well:
[Player.log](https://github.com/natmlx/videokit/files/13629542/Player.log)

I really need to get any framework crash issues like these resolved for my users as soon as possible - hopefully this is viewed as critical.

Thank you

**Comment by pnostudiodeveloper** [comment]
While testing today, I found another issue in my code that could possibly have been responsible for the Camera view not starting - I am waiting to hear back from the user who reported the issue to see if the code changes have solved the framework crash for them - I will let you know.  


Regardless of whether or not this remains a critical error, I think it's important that the framework correctly report errors - this error currently suggests that something is wrong with the NatML subscription.

**Comment by pnostudiodeveloper** [comment]
I heard back from the user - 

- Using the Try Catch to catch the error did not fix the issue - the Camera View error is caught and the error no longer appears in the log, but the camera view does not start.


- Please, can you elevate this to a bug? 

- Are you absolutely sure this couldn't have something to do with the subscription verification, which is what the error message specifically referred to?

**Comment by olokobayusuf** [comment]
Can you add your code that sets the camera device? Make sure to use code tags. Here's what I can deduce:

1. The error is specifically being raised when you set the camera device on the camera manager. The manager will try to start the camera preview with the new device you set *if the manager was running*. This is what makes switching cameras work easily. From the error, the camera manager is running when you set the new device.

2. Discovering cameras should properly setup the session token, if it isn't already setup. On Windows, when a session token is set, the native implementation will log the token along with the status. This doesn't show up in the logs you shared.

3. It's not clear why the token isn't being logged natively. A managed exception should be raised if any of the steps involved fails. But none of that is present in the logs.

**Comment by pnostudiodeveloper** [comment]
Sorry - adding to GitHub with code tags.

- - - - - - - - - - - - - - - - - - - - - -

SeeMusic App

www.seemusicapp.com

**Comment by pnostudiodeveloper** [comment]
`CameraDevice[] devices = await CameraDevice.Discover();


            if (devices.Length > 0 && MIDIControl.Instance.selectedVideoInput < devices.Length)
            {
                try
                {
                    CameraManager.device = devices[MIDIControl.Instance.selectedVideoInput];


                    switch (SceneSingleton.Instance.CameraFramerate)
                    {
                        case 30:
                            CameraManager.frameRate = VideoKitCameraManager.FrameRate._30;
                            break;

                        case 60:
                            CameraManager.frameRate = VideoKitCameraManager.FrameRate._60;
                            break;

                        case 120:
                            CameraManager.frameRate = VideoKitCameraManager.FrameRate._120;
                            break;
                    }

                    switch (SceneSingleton.Instance.CameraResolution)
                    {
                        case "480p":
                            CameraManager.resolution = VideoKitCameraManager.Resolution._640x480;
                            break;

                        case "720p":
                            CameraManager.resolution = VideoKitCameraManager.Resolution._1280x720;
                            break;

                        case "1080p":
                            CameraManager.resolution = VideoKitCameraManager.Resolution._1920x1080;
                            break;

                        case "4K":
                            CameraManager.resolution = VideoKitCameraManager.Resolution._4K;
                            break;

                    }

                    await CameraManager.StartRunning();

                    if (CameraManager.device.previewResolution.height > 0)
                    {
                        CameraAspect = (float)CameraManager.device.previewResolution.width / (float)CameraManager.device.previewResolution.height;
                    }

                    aspectFitter.aspectRatio = CameraAspect;

                }
                catch
                {
                    Debug.Log("Failed to start Camera");
                }
            }`

**Comment by pnostudiodeveloper** [comment]
Given what you're telling me - I searched for any code that sets the CameraManager.device.

The old version of NatCorder used to have crashes if the camera device was changed or restarted when it was still running.

To that aim, I have code that sets the device to be null and stops the Camera before restarting it again:

`   if (CameraManager.device != null)
        {
            CameraManager.device.StopRunning();

            CameraManager.device = null;
        }

        CameraManager.StopRunning();
`

Could this code block possibly be contributing to this issue in some way?

**Comment by pnostudiodeveloper** [comment]
- The user tested a mono build of a blank project I created that has only a CameraManager and CameraView component added to a Canvas object

- It replicates the same issue in the Log.   Log file attached
[Player.log](https://github.com/natmlx/videokit/files/13656704/Player.log)


- A note:   When the user reinstalls the previous version of my app that uses NatCorder, their camera works perfectly on the same computer.

**Comment by pnostudiodeveloper** [comment]
- It seems clear from testing information this is reproducible outside my app in the simplest possible project, with no added code.

- I understand that you're slammed with issues right now.  Do you think there's any chance this issue could get resolved before the holidays?  

- If you think it's very unlikely it will get resolved soon, I should try to revert the framework on Windows today, which will be very difficult, but ultimately less stressful than users emailing over the holidays about the issue.


Thank you

**Comment by olokobayusuf** [comment]
Fixed in 0.0.19.
