### ISSUE TITLE
Add Prores 4444 (incl. alpha channel) and other formats

### ISSUE THREAD

**Issue by jakemelt** [natmlx/videokit#89]
Our needs currently are specifically for MacOS (Arm), but considering that (some) current iPhones and iPads support ProRes recording and playback, would be great to have the option for those devices as well.

HDR Recording would be an added bonus - which again should already be supported with current iOS devices?

**Comment by olokobayusuf** [comment]
@jakemelt we will likely get ProRes 4444 support in the next update (0.0.18). I should note that VideoKit doesn't do video playback; it only does video recording. Furthermore, we don't plan to support HDR recording yet; just SDR.

**Comment by olokobayusuf** [comment]
This has been added to the 0.0.18 release.

**Comment by olokobayusuf** [comment]
@jakemelt you can test this out now with the [VideoKit 0.0.18 alpha](https://www.npmjs.com/package/ai.natml.videokit). VideoKit 0.0.18 will be out early next week.
