### ISSUE TITLE
webgl-camera-error bug

### ISSUE THREAD

**Issue by stusman** [natmlx/videokit#90]
Hello. This problem appeared after I do  videoKitCameraManager.StartRunning(). After the build on webgl. VideoKit version 0.0.17.
```c#
ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
``` 

My full stack trace of the exception:
[_videokit.log](https://github.com/natmlx/videokit/files/13839761/_videokit.log)

My code:
![image](https://github.com/natmlx/videokit/assets/33695500/dee2fc18-8272-4705-9452-c5011b41715d)

**Comment by olokobayusuf** [comment]
Fixed in [VideiKit 0.0.18](https://www.npmjs.com/package/ai.natml.videokit).
