### ISSUE TITLE
Bad audio quality

### ISSUE THREAD

**Issue by pabloleban** [natmlx/videokit#91]
I can hear some clicking noises in the recording.

Here are the recording vs how it should sound:

[how it actually sounds.zip](https://github.com/natmlx/videokit/files/13864661/how.it.actually.sounds.zip)

I've noticed that this starts to happen when a sound reaches a specific gain volume. To easily test this, increase the volume of a sound by either reproducing the same sound in multiple audio sources at the same time, or simply by using the Audio Mixer in Unity.

Here's a repro: https://github.com/pabloleban/videokit-sound-bug

**Comment by olokobayusuf** [comment]
Thanks for opening!

**Comment by pabloleban** [comment]
any update on this?

**Comment by olokobayusuf** [comment]
None yet, but we can add attenuation to prevent cackling for high volume audio. This would likely be fixed in 0.0.19.

**Comment by olokobayusuf** [comment]
@pabloleban we've decided not to add attenuation, because downstream recording APIs don't do it themselves either. You'll have to implement a workaround in your own code. I'm happy to share steps on doing so.
