### ISSUE TITLE
Feature Request: Share text only

### ISSUE THREAD

**Issue by thammin** [natmlx/videokit#92]
```c#
using var payload = new SharePayload();
payload.AddText("some texts");
await payload.Share();
```
Hello, I've used to share text only as the code showed above using the NatShare plugin.
Can you please make this plugin able to share text only? Thanks.

**Comment by olokobayusuf** [comment]
This has been implemented for a while:
```
var asset = await MediaAsset.FromText("this is some text");
await asset.Share();
```
