### ISSUE TITLE
Only initialize VideoKit when it get's actually used

### ISSUE THREAD

**Issue by marvpaul** [natmlx/videokit#96]
As we discussed previously it would be great to only init VideoKit when it actually get's used. This would be a great workaround for the crash i'm facing at the moment with VideoKit when starting Unity as a live wallpaper service.

**Comment by marvpaul** [comment]
@lanreolokoba this is related to this issue: https://github.com/natmlx/videokit/issues/94
When VideoKit only get initialized when it's used, the above mentioned crash would most likely not happen as I don't use any VideoKit / NatML functionality within the live wallpaper.

**Comment by olokobayusuf** [comment]
@marvpaul please follow up on this when you can :)

**Comment by marvpaul** [comment]
Solved - thank you!

**Comment by olokobayusuf** [comment]
Great!
