### ISSUE TITLE
Memory Leak on VideoKitCameraManager

### ISSUE THREAD

**Issue by HyundongHwang** [natmlx/videokit#99]
As shown in the picture below, a memory leak always occurs even when only the camera is rendered using the basic VideoKitCameraManager without a separate script.

I checked because crashes occur frequently in scenes using the cam on Android devices, and the same issue exists in MacOS Player.

To prevent memory leaks, did I miss something by adding script code or a separate implementation?

- OS : MacOS M2 14.1.1(23B81)
- Unity : 2022.3.11f1
- VideoKit : 0.0.18-alpha.3

<img width="1710" alt="image" src="https://github.com/natmlx/videokit/assets/5696570/023aeaee-37a3-49da-b991-f4f939d07da6">

**Comment by olokobayusuf** [comment]
Hey @HyundongHwang , thanks for reporting this. We'll try to reproduce and get back to you.

**Comment by HyundongHwang** [comment]
@olokobayusuf 
Thank you for your kind reply.
However, this problem is not a problem in actual AOS iOS devices, and it is normal even with the profiler.
I'm not sure if it's just the display of the profiler in the MacOS editor that's the problem.
So, I think it would be okay to close the issue without tracking it.
